name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
     # Create APK Debug
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug

    # Upload Artifact Build
    # Noted For Output [module-name]/build/outputs/
    - name: Upload debug build APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: App bundle(s) and APK(s) generated
        path: app/build/outputs/
